CREATE TABLE dra_perpetual_rights_migration_input_us (
    id int4 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 10000000 START 1 CACHE 1 NO CYCLE) NOT NULL,
    country_id bpchar(3) NULL,
    "Artist" varchar(500) NULL,
    "Roster Status" varchar(50) NULL,
    "Contract" varchar(255) NULL,
    "Doc Type" varchar(255) NULL,
    "Release Label" varchar(255) NULL,
    "Project Id" int4 NULL,
    "Project Number" int4 NULL,
    "Project Name" varchar(255) NULL,
    "Signed Status" varchar(50) NULL,
    "Contract Status" varchar(50) NULL,
    "Period" varchar(255) NULL,
    "Recording" varchar(255) NULL,
    "Territory" varchar(3000) NULL,
    "Contract Master Clearance" varchar(50) NULL,
    "Period Master Clearance" varchar(50) NULL,
    "Recording Master Clearance" varchar(50) NULL,
    "Terms of Exploitation" varchar(255) NULL,
    "Ownership" varchar(255) NULL,
    "Perpetual Rights" varchar(50) NULL,
    "Perpetual Rights Exception" varchar(50) NULL,
    status_flag varchar(1) NULL,
    mod_stamp timestamp NULL,
    mod_user numeric(22) NULL,
    CONSTRAINT dra_perpetual_rights_migration_input_us_pkey PRIMARY KEY (id)
);