CREATE TABLE dra_perpetual_rights_migration_protocol (
         id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
         action_id numeric(22) NOT NULL,
         document_id numeric(22) NULL,
         contract_id numeric(22) NULL,
         contract_number varchar(255) NULL,
         recording varchar(255) NULL,
         dra_perpetual_rights_migration_input_id numeric(22) not NULL,
         input_level_node_instance_id numeric(22) NULL,
         digital_rights_contract_eu_id numeric(22) NULL,
         digital_rights_contract_us_id numeric(22) NULL,
         mod_stamp timestamp NOT NULL,
         mod_user numeric(22) NOT NULL,
         result_status varchar(10) NOT NULL,
         "result" text NULL,
         status_flag varchar(1) NULL,
         CONSTRAINT dra_perpetual_rights_migration_protocol_pkey PRIMARY KEY (id)
)