CREATE TABLE dra_perpetual_rights_migration_input_eu (
    id int4 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 10000000 MAXVALUE 2147483647 START 10000000 CACHE 1 NO CYCLE) NOT NULL,
    country_id bpchar(3) NULL,
    "Artist" varchar(500) NULL,
    "Contract" varchar(255) NULL,
    "Doc Type" varchar(255) NULL,
    "Contracting Company" varchar(255) NULL,
    "Project Id" int4 NULL,
    "Project Number" int4 NULL,
    "Project Name" varchar(255) NULL,
    "Product Family Id" int4 NULL,
    "Product Title" varchar(255) NULL,
    "Only Products and/or Tracks" varchar(50) NULL,
    "Status of Term" varchar(50) NULL,
    "Approval Status" varchar(50) NULL,
    "Period" varchar(255) NULL,
    "Recording" varchar(255) NULL,
    "Territory" varchar(3000) NULL,
    "Term Related Provisions Exploitation Period End" varchar(50) NULL,
    "Exploitation End" varchar(50) NULL,
    "Dates(s) cleaned - Automatic Date Calculation" varchar(50) NULL,
    "Contract Master Clearance" varchar(50) NULL,
    "Period Master Clearance" varchar(50) NULL,
    "Recording Master Clearance" varchar(50) NULL,
    "Perpetual Rights" varchar(50) NULL,
    "Perpetual Rights Exception" varchar(50) NULL,
    status_flag varchar(1) NULL,
    mod_stamp timestamp NULL,
    mod_user numeric(22) NULL,
    CONSTRAINT dra_perpetual_rights_migration_input_eu_pkey PRIMARY KEY (id)
);